from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import cohen_kappa_score, confusion_matrix

from src import config
from src.build_retest_batch import BATCH_QUOTAS, LABEL_COLUMNS, VISIBLE_COLUMNS, select_rows

GOLDEN_DIR = config.PROJECT_ROOT / "golden"
GOLDEN_SET = GOLDEN_DIR / "golden_set_v1.csv"

TAXONOMY_LABELS = [
    "flight_delay", "flight_cancellation_rebooking", "baggage", "seating_and_upgrade",
    "boarding_and_gate", "booking_fees_and_fare_rules", "staff_and_service_complaint",
    "loyalty_and_lounge", "praise_and_compliment", "general_dissatisfaction",
    "non_support_commentary", "OTHER", "UNCLEAR",
]
CONFIDENCE_VALUES = {"high", "medium", "low"}
FLAG_TRUE = {"yes"}

FROZEN_ARTIFACTS = [
    "golden_set_v1.csv", "b01_pilot_labelled.csv", "b02_fresh_labelled.csv",
    "golden_exclusion_ids.txt", "golden_customer_exclusion_ids.txt",
]

BOOTSTRAP_RESAMPLES = 2_000
BOOTSTRAP_SEED = 44
MIN_N_FOR_RATE = 3

ORIGINAL_ANNOTATION_DATE = "2026-09-15 (b01 20:26, b02 22:43)"
RETEST_DATE = "2026-09-16 10:36"
GAP_DESCRIPTION = "approximately 12-14 hours"


def file_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def frozen_digests() -> dict:
    return {name: file_digest(GOLDEN_DIR / name) for name in FROZEN_ARTIFACTS}


def validate_retest(frame: pd.DataFrame) -> dict:
    expected_ids = [f"rt_{i:03d}" for i in range(1, 46)]
    forbidden = ["annotation_id", "conversation_id", "tweet_id", "batch", "created_at",
                 "sampling_stratum", "customer_author_id", "original_primary_intent"]
    return {
        "row_count": len(frame),
        "row_count_is_45": len(frame) == 45,
        "retest_id_unique": not frame["retest_id"].duplicated().any(),
        "retest_ids_complete": sorted(frame["retest_id"]) == expected_ids,
        "primary_intent_complete": int((frame["primary_intent"].str.strip() == "").sum()) == 0,
        "invalid_primary": sorted({v for v in frame["primary_intent"] if v.strip() and v not in TAXONOMY_LABELS}),
        "invalid_secondary": sorted({v for v in frame["secondary_intent"] if v.strip() and v not in TAXONOMY_LABELS}),
        "invalid_confidence": sorted({v for v in frame["confidence"] if v.strip() and v.lower() not in CONFIDENCE_VALUES}),
        "invalid_flags": sorted({v for c in ("is_ambiguous", "needs_discussion")
                                 for v in frame[c] if v.strip() and v.lower() not in FLAG_TRUE}),
        "notes_are_text": bool(frame["notes"].map(lambda v: isinstance(v, str)).all()),
        "forbidden_columns_present": [c for c in forbidden if c in frame.columns],
        "columns": list(frame.columns),
        "unexpected_columns": [c for c in frame.columns if c not in VISIBLE_COLUMNS + LABEL_COLUMNS],
    }


def reconstruct_blank(golden: pd.DataFrame, seed: int, temp_dir: Path) -> pd.DataFrame:
    rows = select_rows(golden, seed)
    blank = rows[VISIBLE_COLUMNS].copy()
    for column in LABEL_COLUMNS:
        blank[column] = ""
    temp_dir.mkdir(parents=True, exist_ok=True)
    blank.to_csv(temp_dir / "reconstructed_blank.csv", index=False, encoding="utf-8-sig")
    return blank


def bootstrap_kappa(original: np.ndarray, retest: np.ndarray, resamples: int, seed: int) -> dict:
    rng = np.random.default_rng(seed)
    n = len(original)
    scores = []
    degenerate = 0
    for _ in range(resamples):
        idx = rng.integers(0, n, n)
        score = cohen_kappa_score(original[idx], retest[idx], labels=TAXONOMY_LABELS)
        if np.isnan(score):
            degenerate += 1
            continue
        scores.append(score)
    scores = np.array(scores)
    return {
        "method": (
            f"Non-parametric percentile bootstrap. {resamples} resamples of the {n} "
            "(original, retest) label pairs, drawn with replacement, seed "
            f"{seed}. Cohen's kappa recomputed on each resample over the fixed 13-class "
            "label set; the 95% interval is the 2.5th and 97.5th percentiles of the "
            "resulting distribution."
        ),
        "resamples": resamples,
        "seed": seed,
        "usable_resamples": int(len(scores)),
        "degenerate_resamples": degenerate,
        "ci_lower": round(float(np.percentile(scores, 2.5)), 4),
        "ci_upper": round(float(np.percentile(scores, 97.5)), 4),
        "bootstrap_mean": round(float(scores.mean()), 4),
    }


def render_report(stats: dict) -> str:
    agree, per_intent, conf = stats["agreement"], stats["per_intent"], stats["confidence_analysis"]
    lines = [
        "# Phase 5 — Intra-annotator short-gap test-retest agreement",
        "",
        "Generated by `src/analyse_retest.py`. All frozen artifacts are read-only.",
        "",
        "> **The original annotations were completed on 2026-09-15 and the retest was "
        "completed approximately 12–14 hours later on 2026-09-16. This is therefore a "
        "short-gap test-retest. Residual memory may materially inflate agreement, so the "
        "resulting statistic is provisional and should not be interpreted as a clean "
        "long-gap reliability estimate.**",
        "",
        "> **This is a single-annotator test-retest measurement. It measures consistency "
        "of applying the taxonomy over time, not reproducibility across independent "
        "annotators.**",
        "",
        "## Setup",
        "",
        f"- Original annotation: {stats['original_annotation_date']}",
        f"- Retest annotation: {stats['retest_date']}",
        f"- **Actual gap: {stats['gap']}** (the plan had specified ~7 days)",
        f"- Retest size: **{stats['n']}** examples ({stats['batch_strata']})",
        f"- Label set: all **{len(TAXONOMY_LABELS)}** taxonomy v2 classes, fixed",
        "",
        "## Headline results",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Raw agreement | **{agree['raw_agreement_pct']}%** ({agree['matches']}/{stats['n']}) |",
        f"| Cohen's kappa | **{agree['cohens_kappa']}** |",
        f"| 95% bootstrap CI | **[{stats['bootstrap']['ci_lower']}, {stats['bootstrap']['ci_upper']}]** |",
        "",
        "No judgement is offered here on whether this value is good or bad. It is "
        "reported with its uncertainty; the interval is wide because 45 items spread "
        "over 13 classes cannot pin kappa down precisely.",
        "",
        "### Bootstrap method",
        "",
        stats["bootstrap"]["method"],
        "",
        f"Usable resamples: {stats['bootstrap']['usable_resamples']} of "
        f"{stats['bootstrap']['resamples']}"
        + (f"; {stats['bootstrap']['degenerate_resamples']} discarded as degenerate "
           "(a resample containing a single label makes kappa undefined)."
           if stats["bootstrap"]["degenerate_resamples"] else "."),
        "",
        "## Per-intent agreement",
        "",
        "Grouped by the **original** label. A rate is shown only where n >= "
        f"{MIN_N_FOR_RATE}; smaller groups cannot support an estimate.",
        "",
        "| original intent | n | matched | agreement |",
        "| --- | --- | --- | --- |",
    ]
    for row in per_intent:
        rate = f"{row['agreement_pct']}%" if row["assessable"] else "_Not assessable at this sample size._"
        lines.append(f"| `{row['intent']}` | {row['n']} | {row['matched']} | {rate} |")

    lines += [
        "",
        "## Disagreements",
        "",
        f"{stats['n'] - agree['matches']} of {stats['n']} labels changed between the two "
        "passes.",
        "",
    ]
    if stats["disagreement_pairs"]:
        lines += ["| original → retest | count |", "| --- | --- |"]
        lines += [f"| `{pair}` | {count} |" for pair, count in stats["disagreement_pairs"]]
        lines += [
            "",
            "These are **measured disagreements**, not evidence that either label is "
            "correct. The purpose is to measure consistency, and the original label has "
            "no privileged status.",
            "",
        ]
        lines += ["**Examples** (retest id and excerpt only; original identifiers withheld):", ""]
        lines += [
            f"- `{d['retest_id']}` `{d['original']}` → `{d['retest']}` — {d['excerpt']}"
            for d in stats["disagreement_examples"]
        ]
        lines.append("")

    lines += [
        "### Confusion matrix (non-zero cells only)",
        "",
        "| original | retest | count |",
        "| --- | --- | --- |",
    ]
    lines += [
        f"| `{cell['original']}` | `{cell['retest']}` | {cell['count']} |"
        for cell in stats["confusion_non_zero"]
    ]
    lines += [
        "",
        f"The full {len(TAXONOMY_LABELS)}x{len(TAXONOMY_LABELS)} matrix is in the JSON; "
        "over 45 items it is almost entirely zeros, so only populated cells are shown here.",
        "",
        "## Agreement by original confidence",
        "",
        "Grouped by the confidence recorded during the **original** pass. Retest "
        "confidence is reported separately below and plays no part in this calculation.",
        "",
        "| original confidence | n | matched | agreement | note |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in conf["by_original_confidence"]:
        rate = f"{row['agreement_pct']}%" if row["assessable"] else "—"
        note = "" if row["assessable"] else f"unstable: n={row['n']}"
        lines.append(f"| {row['confidence']} | {row['n']} | {row['matched']} | {rate} | {note} |")

    lines += [
        "",
        f"Retest confidence distribution (not used in the agreement metric): "
        f"{conf['retest_confidence_distribution']}",
        "",
        "## Limitations",
        "",
        "1. **One annotator only.** No inter-annotator agreement exists for this dataset.",
        "2. **45 examples.** Small for a 13-class problem; several classes appear once or "
        "not at all.",
        f"3. **The gap was {stats['gap']}**, not the seven days originally planned.",
        "4. **Residual memory may inflate agreement.** With an overnight gap on items seen "
        "the previous day, some agreement may reflect recall of the earlier decision "
        "rather than independent re-derivation.",
        "5. **The statistic is provisional.** It is an upper bound on labelling "
        "reliability, and a short-gap upper bound at that.",
        "6. **Some original labels may have been influenced by ChatGPT reviewer "
        "suggestions.** The annotator made every final decision, but the influence is "
        "not zero.",
        "7. **That influence may recur at retest**, inflating self-agreement further, "
        "since the same reasoning can resurface.",
        "8. **Consequently, later LLM-judge agreement must not be presented as "
        "independent human corroboration.** Shared influence would inflate it, and that "
        "must be disclosed in the LLM-judge phase.",
        "9. **Rare intents have unstable per-intent estimates** and are marked not "
        "assessable rather than given a misleading percentage.",
        "",
        "## What this does and does not support",
        "",
        "Supported: a provisional statement about whether one person applies taxonomy v2 "
        "consistently over a short interval, and an empirical map of which category "
        "boundaries are unstable in practice.",
        "",
        "Not supported: any claim about reproducibility across annotators, any claim that "
        "one label in a disagreeing pair is correct, and any use of this figure as "
        "validation of the taxonomy itself.",
        "",
        "The taxonomy has **not** been changed on the basis of these results.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyse the intra-annotator retest.")
    parser.add_argument("--run", default="r01")
    parser.add_argument("--seed", type=int, default=BOOTSTRAP_SEED)
    args = parser.parse_args()

    digests_before = frozen_digests()
    labelled_path = GOLDEN_DIR / f"retest_{args.run}_labelled.csv"
    if not labelled_path.exists():
        raise FileNotFoundError(f"Labelled retest not found at {labelled_path}")

    retest = pd.read_csv(labelled_path, dtype=str, keep_default_na=False, encoding="utf-8-sig")
    validation = validate_retest(retest)
    failures = [
        key for key, value in validation.items()
        if (isinstance(value, bool) and not value) or (key.startswith(("invalid", "forbidden", "unexpected")) and value)
    ]
    if failures:
        raise RuntimeError(f"Retest validation failed: {failures}")

    golden = pd.read_csv(GOLDEN_SET, dtype=str, keep_default_na=False, encoding="utf-8-sig")
    temp_dir = Path(config.PROJECT_ROOT / ".retest_tmp")
    reconstructed = reconstruct_blank(golden, args.seed, temp_dir)

    reconstruction = {
        "row_count_matches": len(reconstructed) == len(retest),
        "retest_ids_identical_and_ordered": reconstructed["retest_id"].tolist() == retest["retest_id"].tolist(),
        "texts_identical_and_ordered": reconstructed["text"].tolist() == retest["text"].tolist(),
        "text_identity_count": int((reconstructed["text"].values == retest["text"].values).sum()),
    }
    if not all(v for k, v in reconstruction.items() if isinstance(v, bool)):
        raise RuntimeError(f"Reconstruction mismatch: {reconstruction}")

    key = json.loads(
        (config.REPORTS_DIR / f"phase5_retest_{args.run}_key.json").read_text(encoding="utf-8")
    )["mapping"]
    golden_by_id = golden.set_index("annotation_id")
    mapped = [key[rid] for rid in retest["retest_id"]]
    annotation_ids = [m["annotation_id"] for m in mapped]
    reconstruction["key_maps_1to1"] = len(set(annotation_ids)) == len(retest) == 45
    reconstruction["all_map_into_golden"] = set(annotation_ids) <= set(golden["annotation_id"])
    if not (reconstruction["key_maps_1to1"] and reconstruction["all_map_into_golden"]):
        raise RuntimeError("Retest key does not map cleanly onto the frozen golden set")

    original = golden_by_id.loc[annotation_ids, "primary_intent"].to_numpy()
    original_conf = golden_by_id.loc[annotation_ids, "confidence"].to_numpy()
    current = retest["primary_intent"].to_numpy()

    matches = int((original == current).sum())
    kappa = float(cohen_kappa_score(original, current, labels=TAXONOMY_LABELS))
    bootstrap = bootstrap_kappa(original, current, BOOTSTRAP_RESAMPLES, args.seed)

    per_intent = []
    for intent in TAXONOMY_LABELS:
        mask = original == intent
        n = int(mask.sum())
        if n == 0:
            continue
        matched = int((current[mask] == intent).sum())
        per_intent.append({
            "intent": intent, "n": n, "matched": matched,
            "assessable": n >= MIN_N_FOR_RATE,
            "agreement_pct": round(100 * matched / n, 1) if n >= MIN_N_FOR_RATE else None,
        })
    per_intent.sort(key=lambda r: -r["n"])

    disagreement_pairs = Counter(
        f"{o} -> {c}" for o, c in zip(original, current) if o != c
    ).most_common()
    disagreement_examples = [
        {
            "retest_id": rid,
            "original": o,
            "retest": c,
            "excerpt": text[:90],
        }
        for rid, o, c, text in zip(retest["retest_id"], original, current, retest["text"])
        if o != c
    ]

    matrix = confusion_matrix(original, current, labels=TAXONOMY_LABELS)
    confusion_non_zero = [
        {"original": TAXONOMY_LABELS[i], "retest": TAXONOMY_LABELS[j], "count": int(matrix[i][j])}
        for i in range(len(TAXONOMY_LABELS)) for j in range(len(TAXONOMY_LABELS))
        if matrix[i][j] > 0
    ]

    by_confidence = []
    for level in ("high", "medium", "low"):
        mask = original_conf == level
        n = int(mask.sum())
        if n == 0:
            continue
        matched = int((original[mask] == current[mask]).sum())
        by_confidence.append({
            "confidence": level, "n": n, "matched": matched,
            "assessable": n >= MIN_N_FOR_RATE,
            "agreement_pct": round(100 * matched / n, 1) if n >= MIN_N_FOR_RATE else None,
        })

    stats = {
        "measurement_type": "intra-annotator short-gap test-retest agreement",
        "original_annotation_date": ORIGINAL_ANNOTATION_DATE,
        "retest_date": RETEST_DATE,
        "gap": GAP_DESCRIPTION,
        "n": len(retest),
        "batch_strata": BATCH_QUOTAS,
        "validation": validation,
        "reconstruction": reconstruction,
        "agreement": {
            "matches": matches,
            "raw_agreement_pct": round(100 * matches / len(retest), 1),
            "cohens_kappa": round(kappa, 4),
        },
        "bootstrap": bootstrap,
        "per_intent": per_intent,
        "disagreement_pairs": disagreement_pairs,
        "disagreement_examples": disagreement_examples,
        "confusion_labels": TAXONOMY_LABELS,
        "confusion_matrix": matrix.tolist(),
        "confusion_non_zero": confusion_non_zero,
        "confidence_analysis": {
            "by_original_confidence": by_confidence,
            "retest_confidence_distribution": retest["confidence"].value_counts().to_dict(),
        },
        "frozen_digests_before": digests_before,
    }

    config.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    (config.REPORTS_DIR / f"phase5_retest_agreement.json").write_text(
        json.dumps(stats, indent=2, default=str), encoding="utf-8"
    )
    (config.REPORTS_DIR / f"phase5_retest_agreement.md").write_text(
        render_report(stats), encoding="utf-8"
    )

    digests_after = frozen_digests()
    if digests_before != digests_after:
        raise RuntimeError("A frozen artifact changed during analysis")

    for leftover in temp_dir.glob("*"):
        leftover.unlink()
    temp_dir.rmdir()

    print(f"n={stats['n']}  raw={stats['agreement']['raw_agreement_pct']}%  "
          f"kappa={stats['agreement']['cohens_kappa']}  "
          f"CI=[{bootstrap['ci_lower']}, {bootstrap['ci_upper']}]")
    print(f"Report: {config.REPORTS_DIR / 'phase5_retest_agreement.md'}")
    print("Frozen artifacts unchanged.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
